name: Sync Fork

on:  
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行一次  
  workflow_dispatch:

jobs:  
  sync:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout forked repo        
        uses: actions/checkout@v4        
        with:          
          persist-credentials: false      
      - name: Set up git        
        run: |          
          git config --global user.name w19996          
          git config --global user.email 2449016809@qq.com      
      - name: Add upstream        
        run: git remote add upstream https://github.com/acidanthera/OpenCorePkg.git      
      - name: Fetch upstream        
        run: git fetch upstream      
      - name: Merge upstream changes        
        run: git merge upstream/main --no-edit      
      - name: Push changes to fork        
        run: |          
          git push origin main
