name: Sync Fork

on:  
  schedule:
    - cron: '40 6 * * *'  # 每天北京时间11:30运行  
  workflow_dispatch:

jobs:  
  sync:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout forked repo        
        uses: actions/checkout@v4        
        with:          
          persist-credentials: false      
      - name: Set up git        
        run: |          
          git config --global user.name w19996          
          git config --global user.email 2449016809@qq.com      
      - name: Add upstream        
        run: git remote add upstream https://github.com/acidanthera/OpenCorePkg.git      
      - name: Fetch upstream        
        run: git fetch upstream      
      - name: List remote branches        
        run: git branch -r  # 确认 upstream/master 是否存在      
      - name: Checkout local master branch        
        run: git checkout master  # 确保处于本地 master 分支      
      - name: Pull latest changes from origin        
        run: git pull origin master  # 同步 fork 仓库的 master 分支      
      - name: Merge upstream changes        
        run: git merge upstream/master --no-edit --allow-unrelated-histories -X theirs  # 合并并允许无关历史 
      - name: Set up authentication        
        run: |          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/w19996/OpenCorePkgMOD.git  # 使用 GITHUB_TOKEN 进行身份验证
      - name: Push changes to fork        
        run: git push origin master  # 将更新后的内容推送到 fork
